# JVM args for the Gradle daemon
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.caching=false
# Kotlin/AndroidX
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official

# Disable Build Analyzer to save disk space and avoid IO errors during report generation
android.buildanalyzer.enabled=false
